# https://stuartlab.org/signac/articles/pbmc_vignette

library(Signac)
library(Seurat)
library(GenomicRanges)
library(ggplot2)
library(patchwork)

setwd("./scverse/Signac/data/PBMC10k")
list.files()
# 预处理工作流程

# We start by creating a Seurat object using the peak/cell matrix and cell metadata generated by cellranger-atac, 
# and store the path to the fragment file on disk in the Seurat object:

counts <- Read10X_h5(filename = "10k_pbmc_ATACv2_nextgem_Chromium_Controller_filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "10k_pbmc_ATACv2_nextgem_Chromium_Controller_singlecell.csv",
  header = TRUE,
  row.names = 1
)

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  fragments = "10k_pbmc_ATACv2_nextgem_Chromium_Controller_fragments.tsv.gz",
  min.cells = 10,
  min.features = 200
)

pbmc <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)

pbmc
pbmc[['peaks']]
# 如果没有 .h5 文件，仍可运行分析。您可能有格式化为三个文件的数据，一个计数文件 （.mtx）、一个单元格条形码文件和一个峰值文件。
# 如果是这种情况，您可以使用 Matrix：：readMM（） 函数加载数据

